version: "3"
services:
  webhook-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - USER_ACCESS_TOKEN=EAADg0pPV2X0BAAF8XVGOQIVuJI0ormHxR1TeMZABV2ZCsUJwZAIktOmpwAnnnbII3OZAmUUTDsG8RxDdpmy5iBxzO3NWkpqo3yyDxmv4JMqZB1K2PdCyZBhEZCcf7DMn2fh2vzLcy0JRIkkOtTjJsDL3ZAgZAPMSxvZAXClHYJd5kI7Q8KZAMv7LdCf2lRlXynl7hsftBL29HyBUP8j5SpVpN9E6C5aS7YVQQJPkayUSj6gTAZDZD
      - HUB_VERIFY_TOKEN=8f76f6840a48f64159f30c1ff659e7bd8220f1e4cf31bf44f241e24f
      - PORT=3000
      - PHONE_NUMBER_ID=112688608518505
    restart: "no"
    depends_on:
      - mongo

    # Build, after removing the dist folder in Dockerfile.dev
    command: |
      sh -c "npm run test"
  mongo:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: users
    ports:
      - 27017:27017
