# Use the Node.js 16-alpine base image
FROM node:20-alpine3.17

# Create a new user inside the container
RUN addgroup -S myuser && adduser -S -G myuser myuser

# Set the working directory inside the container
WORKDIR /app

# Make sure a dir is created for logs
RUN mkdir logs

# # Copy the package.json and package-lock.json files to the working directory
COPY package.json package-lock.json ./

# # Install the dependencies
RUN npm ci

# Copy all remaining files to the working directory
COPY . .

# Build Production version / dist
RUN npm run build 

# Set the ownership of the working directory to the new user
RUN chown -R myuser:myuser /app

# Switch to the new user
USER myuser

# Indicate that port 3000 will be opened in this application.
EXPOSE 3000

# Set the command to run the entry point script
# No testing, because (no mongo db is provided)
# If testing use the docker-compose.dev file
# concurrently  \"npm:build:watch\" \"npm:test:watch\" \"nodemon ./dist/server.js\" 
# watch for changes -> test the changes -> restart the dev server
CMD npm run dev
