version: "3"
services:
  webhook-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - VERIFY_TOKEN=""
    volumes:
      - ./dist:/app/dist # Mount the local "dist" directory to the container's "dist" directory
