# Use the Node.js 16-alpine base image
FROM node:20-alpine3.17

# Create a new user inside the container
RUN addgroup -S myuser && adduser -S -G myuser myuser

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy all remaining files to the working directory
COPY . .

# Set the ownership of the working directory to the new user
RUN chown -R myuser:myuser /app

# Build Production version / dist
RUN npm run build

# Switch to the new user
USER myuser

# Indicate that port 3000 will be opened in this application.
EXPOSE 3000

# Set the command to run the entry point script
CMD npm run test && npm run dev
