version: "3"
services:
  webhook-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src:ro
    environment:
      - JWT_SIGNING_KEY_TEST=tHiSiStEsT
    depends_on:
      - mongo
      # Build, after removing the dist folder in Dockerfile.dev
    command: |
      sh -c "npm run test:watch"
  # For testing purposes
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: testDb
    ports:
      - 27017:27017
