# Used for ci/cd workflow
version: "3"
services:
  webhook-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    restart: "no"
    depends_on:
      - mongo

    # Build, after removing the dist folder in Dockerfile.dev
    command: |
      sh -c "npm run test"
  mongo:
    image: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: users
    ports:
      - 27017:27017
